@ECHO OFF

setlocal EnableDelayedExpansion
setlocal

SET HOME=%USERPROFILE:\=/%

SET BUSUFFIX=%1
SET ARCH=%2
SET CPU=%BUSUFFIX%%ARCH%
SET CPUGEN=%ARCH%
if DEFINED ARCH (
	GOTO %ARCH%
) else (
  SET CPUDIR=%CPU%
)
goto AfterCPU

:v7le
SET CPUDIR=%BUSUFFIX%le-v7
SET BUSUFFIX=%BUSUFFIX%v7
goto AfterCPU

:a9
SET CPUDIR=%BUSUFFIX%le-v7
SET CPU=%BUSUFFIX%v7le
SET BUSUFFIX=%BUSUFFIX%v7
SET CPUGEN=a9
goto AfterCPU

:AfterCPU

if DEFINED STAGE_DIR (
  SET STAGE_DIR=%HOME%/stage/nto
  echo Staging directory could not be determined. Using: %STAGE_DIR%
) else (
  echo Using staging directory: %STAGE_DIR%
)

SET CC_COMMAND=%QNX_HOST%/usr/bin/qcc

if DEFINED BUILDTYPE (
    SET BUILDTYPE=Release
)

if DEFINED PROFILE (
    SET PROFILER_FLAGS=-p
) else (
    SET PROFILER_FLAGS=
)

SET STAGE_LIB=%STAGE_DIR%/%CPUDIR%/lib
SET STAGE_USR_LIB=%STAGE_DIR%/%CPUDIR%/usr/lib
SET STAGE_INC=%STAGE_DIR%/usr/include
SET TARGET_LIB=%QNX_TARGET%/lib
SET TARGET_USR_LIB=%QNX_TARGET%/usr/lib
SET TARGET_INC=%QNX_TARGET%/usr/include

SET COMP_PATHS=-Wl,-rpath-link,%STAGE_LIB% ^
    -Wl,-rpath-link,%STAGE_USR_LIB% ^
    -L%STAGE_LIB% ^
    -L%STAGE_USR_LIB% ^
    -L%TARGET_LIB% ^
    -L%TARGET_USR_LIB% ^
    -I%STAGE_INC% ^
    -I%STAGE_INC%/freetype2 ^
    -I%TARGET_INC%

if DEFINED CCWRAP (
    SET CMAKE_EXTRA_OPTIONS=-DCMAKE_C_COMPILER_ARG1=qcc ^
        -DCMAKE_CXX_COMPILER_ARG1=qcc
    SET CC_COMMAND=%CCWRAP%
)

GOTO CPUGEN%CPUGEN%

:CPUGENv7le
REM We have nothing special for this CPU right now
GOTO AfterCPUGEN

:CPUGENa9
SET CMAKE_EXTRA_OPTIONS=-DTARGET_IS_WINCHESTER=1 ^
	%CMAKE_EXTRA_OPTIONS%
GOTO AfterCPUGEN

:AfterCPUGEN

cmake ^
    -DCMAKE_SYSTEM_PROCESSOR="%CPUDIR%" ^
    -DCMAKE_SYSTEM_NAME="QNX" ^
    -DCMAKE_SYSTEM_VERSION="1" ^
    -DCMAKE_BUILD_TYPE="%BUILDTYPE%" ^
    -DCMAKE_C_COMPILER=%CC_COMMAND% ^
    -DCMAKE_C_FLAGS="-Vgcc_nto%CPU% -fpic -g %COMP_PATHS% %PROFILER_FLAGS%" ^
    -DCMAKE_CXX_FLAGS="-Vgcc_nto%CPU% -Y_gpp -fpic -g -lang-c++ %COMP_PATHS% %PROFILER_FLAGS%" ^
    -DCMAKE_INCLUDE_PATH="%STAGE_INC%;%STAGE_INC%/skia" ^
    -DCMAKE_LIBRARY_PATH="%STAGE_LIB%;%STAGE_USR_LIB%" ^
    -DCMAKE_INSTALL_PREFIX="%STAGE_DIR%" ^
    -DCMAKE_OPENCV_GCC_VERSION="42" ^
    -DCMAKE_OPENCV_GCC_VERSION_NUM="402" ^
    -DCMAKE_AR="%QNX_HOST%/usr/bin/nto%BUSUFFIX%-ar" ^
    -DCMAKE_RANLIB="%QNX_HOST%/usr/bin/nto%BUSUFFIX%-ranlib" ^
    -DCMAKE_LD="%QNX_HOST%/usr/bin/nto%BUSUFFIX%-ld" ^
    -DCMAKE_LINKER="%QNX_HOST%/usr/bin/nto%BUSUFFIX%-ld" ^
    -DECLIPSE_CDT4_GENERATE_SOURCE_PROJECT=TRUE ^
    -DBUILD_DOCS=OFF ^
    -DBUILD_NEW_PYTHON_SUPPORT=OFF ^
    -DBUILD_PACKAGE=OFF ^
    -DBUILD_TESTS=OFF ^
    -DWITH_1394=OFF ^
    -DWITH_CUBLAS=OFF ^
    -DWITH_CUDA=OFF ^
    -DWITH_CUFFT=OFF ^
    -DWITH_EIGEN=OFF ^
    -DWITH_FFMPEG=OFF ^
    -DWITH_GSTREAMER=OFF ^
    -DWITH_GTK=OFF ^
    -DWITH_JASPER=OFF ^
    -DWITH_JPEG=OFF ^
    -DWITH_OPENEXR=OFF ^
    -DWITH_OPENGL=OFF ^
    -DWITH_OPENNI=OFF ^
    -DWITH_PNG=OFF ^
    -DWITH_PVAPI=OFF ^
    -DWITH_QT=OFF ^
    -DWITH_TBB=OFF ^
    -DWITH_TIFF=OFF ^
    -DWITH_UNICAP=OFF ^
    -DWITH_V4L=OFF ^
    -DWITH_XINE=OFF ^
    -DQNX=1 ^
    -G"Eclipse CDT4 - Unix Makefiles" ^
    %CMAKE_EXTRA_OPTIONS% ^
    %3 ../

:end
endlocal
